---
- name: Ensure packages are installed
  apk:
    name: "{{ item }}"
    update_cache: yes
  with_items:
      - git
      - curl
      - rsync
      - bash
      - nodejs
      - nodejs-npm
      - libstdc++
      
- name: Install additional packages 
  apk:
    name: "{{ item }}"
    update_cache: yes
  when: additional_packages
  with_items: "{{ additional_packages }}"
  
- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755
    
- name: Copy all node data
  command: rsync -auvh --checksum --delete --chown=root:root /tmp/nodeapp/ /var/www/ --exclude node_modules
 
- name: Get npm version
  command: node -p -e "require('/var/www/package.json').engines.npm || '5.8.0'"
  register: npm_version
  
- name: Install npm package.
  command: "npm install npm@{{ npm_version.stdout }} -g --unsafe-perm"
  args:
    chdir: /var/www

- name: Get node version
  command: node -p -e "require('/var/www/package.json').engines.node || '8.9.4'"
  register: node_version
 
- name: Install node-bin-setup
  command: npm install node-bin-setup -g --unsafe-perm
  
- name: Check current node version
  shell: test "$(node -v 2> /dev/null)" = v{{node_version.stdout}}
  register: nodejs_installed
  ignore_errors: true
 
- name: Install node node.js package.
  command: "npm install node@{{ node_version.stdout }} -g --unsafe-perm"
  args:
    chdir: /var/www
  when: nodejs_installed|failed
 
- name: Prune all packages (cleanup before install)
  command: npm prune --only=prod --verbose
  args:
    chdir: /var/www
  ignore_errors: true

- name: Dedupe all packages (cleanup before install)
  command: npm dedupe --verbose
  args:
    chdir: /var/www
  ignore_errors: true

- name: Install packages based on package.json.
  command: npm install --only=prod --legacy-bundling --verbose
  args:
    chdir: /var/www
    
#- name: Cleanup npm and node
#  file:
#    path: "{{ item }}"
#    state: absent
#  with_items:
#    - /var/www/node_modules/npm
#    - /var/www/node_modules/node
#    - /opt/node/lib/node_modules/node/lib/node_modules
    
- name: Clean up npm cache
  command: npm cache clean --force
  args:
    chdir: /var/www

- name: Remove unnecessary packages
  apk:
    name: "{{ item }}"
    state: absent
  with_items:
      - git
      - rsync
      - bash
      - libstdc++
