---
- name: Ensure packages are installed
  apt:
    name: "{{ item }}"
  with_items:
      - rsync
      - git
  update_cache: yes

- name: Install additional packages 
  apt:
    name: "{{ item.key }}={{ item.value.version }}"
    force: yes
  when: additional_packages
  with_dict: "{{ additional_packages }}"
  update_cache: yes
  ignore_errors: True

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755
    
- name: Copy all node data
  command: rsync -auvh --checksum --delete --chown=root:root /tmp/nodeapp/ /var/www/ --exclude node_modules
  
- name: Install npm package.
  command: "npm install npm@5.8.0 -g --unsafe-perm"
  args:
    chdir: /var/www

- name: Get node version
  command: node -p -e "require('/var/www/package.json').dependencies.node || '8.9.4'"
  register: node_version
 
- name: Install node-bin-setup
  command: npm install node-bin-setup
 
- name: Install node node.js package.
  command: "npm install node@{{ node_version.stdout }} -g --unsafe-perm"
  args:
    chdir: /var/www

- name: Install packages based on package.json.
  command: npm install --production --unsafe-perm
  args:
    chdir: /var/www


