---
# tasks file for nodejs

# Running on conductor to fix bridging issue - should be fixed by v1
- shell: route -n | awk '/UG[ \t]/{print $2}'
  register: docker_gateway

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Copy all node data
  command: cp -r /tmp/nodeapp/ /var/www

- name: Install packages based on package.json.
  npm:
    path: /var/www/nodeapp
    registry: "http://{{ docker_gateway.stdout }}:5080"
  register: npm_install
  until: npm_install|success
