---
- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: Install rsync 
  apt:
    name: "{{ item }}"
    allow_unauthenticated: true
    force: yes
  with_items:
    - rsync

- name: Install node
  apt:
    name: "nodejs={{ nodejs_version | default('6.9.5') }}"
    allow_unauthenticated: yes

- name: Install additional packages 
  apt:
    name: "{{ item.key }}={{ item.value.version }}"
  when: additional_packages
  with_dict: "{{ additional_packages }}"

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Copy all node data
  command: rsync -au /tmp/nodeapp/ /var/www

- name: Install packages based on package.json.
  npm:
    path: /var/www/nodeapp
    registry: "http://registry.npmjs.org/"
