---
- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Copy all node data
  command: cp -r /tmp/nodeapp/ /var/www

- name: Install "n" node.js package globally.
  npm:
    name: n
    global: yes
    registry: "http://registry.npmjs.org/"

- name: install node
  command: n io '6.9.1' -q

- name: install node
  command: node -v

- name: install node
  command: which node

- name: Install packages based on package.json.
  npm:
    path: /var/www/nodeapp
    registry: "http://registry.npmjs.org/"
